is math

link "math.c"

# Here are alot of external functions that
# link to the c library
func acos(float x) float ...
func asin(float x) float ...
func atan(float x) float ...
func cos(float x) float ...
func sin(float x) float ...
func tan(float x) float ...
func log(float x) float ...
func pow(float x, float y) float ...
func sqrt(float x) float ...
func ceil(float x) float ...
func fabs(float x) float ...
func floor(float x) float ...
func fmod(float x, float y) float ...