is io

link "io.c"


# Printing bindings
func nomangle _GN2io5print(string format, ...) ...
func nomangle _GN2io6format(string format, ...) string ...

# func print(string format, ...) {
# 	cprintf(format);
# }

# _GN2io5print
# func __openfile(string path, string mode) byte* ...
# func __readchar(byte* fp) byte ...
# func __fileeof(byte* fp) int ...
# func __filewritestring(byte*fp, string data) int ...
