is _runtime

link "runtime.c"
link "xmalloc.c"
link "../gc/*.o"

# include "std:io"

func xmalloc(int size) byte* ...
func xmalloc_size(byte* ptr) long ...
func __initruntime() ...
func raw_copy(byte* target, int length) byte* ...
func exit(int code) ...